# Generated by Django 5.1.2 on 2024-10-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('temperature', models.IntegerField(verbose_name='temperature')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
    ]
